### ISSUE TITLE
FileNotFoundError: No such file or directory: 'timings.csv'

### ISSUE THREAD

**Issue by BearThatHyper** [Anish-Malla/Zoom-Automation-Python#3]
Whenever I try and open this, it flashes up with a command window that on the bottom line says:
FileNotFoundError: [Errno 2] No such file or directory 'timings.csv'

**Comment by Ryuo1** [comment]
Just as it says, it couldn't find the 'timings.csv' file. You need to create a timings.csv file yourself and put the timings in it.
